spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventos?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: CRbygAtdWGPsFuQZ6HyvFxwkkSxRPe

  jpa:
    show-sql: true
    hibernate:
      dll-auto: update
    properties:
      '[hibernate.format_sql]': true
